// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv3SRTMEd5l-tdkU_8ExJvNyto-ezpN5I',
    appId: '1:409601177280:web:199274f23e0587872f9f25',
    messagingSenderId: '409601177280',
    projectId: 'hotel-7c147',
    authDomain: 'hotel-7c147.firebaseapp.com',
    storageBucket: 'hotel-7c147.appspot.com',
    measurementId: 'G-RJHEJB75CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Lnt5pPKIMXu8xMzJEDrIJm9fnQAOUwI',
    appId: '1:409601177280:android:92e425359dc7e6be2f9f25',
    messagingSenderId: '409601177280',
    projectId: 'hotel-7c147',
    storageBucket: 'hotel-7c147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-_UnvMmU7BZr4BhAot9NGtJ4172Q_P8',
    appId: '1:409601177280:ios:9297e699a9d569ce2f9f25',
    messagingSenderId: '409601177280',
    projectId: 'hotel-7c147',
    storageBucket: 'hotel-7c147.appspot.com',
    iosBundleId: 'com.example.hoteles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-_UnvMmU7BZr4BhAot9NGtJ4172Q_P8',
    appId: '1:409601177280:ios:9297e699a9d569ce2f9f25',
    messagingSenderId: '409601177280',
    projectId: 'hotel-7c147',
    storageBucket: 'hotel-7c147.appspot.com',
    iosBundleId: 'com.example.hoteles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv3SRTMEd5l-tdkU_8ExJvNyto-ezpN5I',
    appId: '1:409601177280:web:1b1ee357e781f1cd2f9f25',
    messagingSenderId: '409601177280',
    projectId: 'hotel-7c147',
    authDomain: 'hotel-7c147.firebaseapp.com',
    storageBucket: 'hotel-7c147.appspot.com',
    measurementId: 'G-GM8F25VKLL',
  );

}